# Generated by Django 4.1.7 on 2023-03-17 15:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuturePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('estimated_cost', models.FloatField()),
                ('target_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('goal', models.CharField(max_length=200)),
                ('target_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='user',
        ),
        migrations.RemoveField(
            model_name='creditscore',
            name='user',
        ),
        migrations.RemoveField(
            model_name='debt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='expensecategory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='financialgoal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='futureexpense',
            name='user',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='investmentoption',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='investmentrecommendation',
            name='option',
        ),
        migrations.RemoveField(
            model_name='investmentrecommendation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='personalizedadvice',
            name='user',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='savingsgoal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sharedfinancialgoal',
            name='users',
        ),
        migrations.RemoveField(
            model_name='sharedgoalcontribution',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='sharedgoalcontribution',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='note',
        ),
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.CharField(default=datetime.datetime(2023, 3, 17, 15, 39, 33, 785922, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.DeleteModel(
            name='CreditCard',
        ),
        migrations.DeleteModel(
            name='CreditScore',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='Debt',
        ),
        migrations.DeleteModel(
            name='ExpenseCategory',
        ),
        migrations.DeleteModel(
            name='FinancialGoal',
        ),
        migrations.DeleteModel(
            name='FutureExpense',
        ),
        migrations.DeleteModel(
            name='Investment',
        ),
        migrations.DeleteModel(
            name='InvestmentOption',
        ),
        migrations.DeleteModel(
            name='InvestmentRecommendation',
        ),
        migrations.DeleteModel(
            name='PersonalizedAdvice',
        ),
        migrations.DeleteModel(
            name='Prediction',
        ),
        migrations.DeleteModel(
            name='SavingsGoal',
        ),
        migrations.DeleteModel(
            name='SharedFinancialGoal',
        ),
        migrations.DeleteModel(
            name='SharedGoalContribution',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AddField(
            model_name='saving',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
        migrations.AddField(
            model_name='income',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
        migrations.AddField(
            model_name='futureplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
    ]
